# Generated by Django 4.1.3 on 2022-12-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedatabase',
            name='display',
            field=models.CharField(default='False', max_length=255),
            preserve_default=False,
        ),
    ]
