# Generated by Django 4.1.3 on 2022-12-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_filedatabase_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedatabase',
            name='notes',
        ),
    ]
