# Generated by Django 4.1.3 on 2022-12-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_filedatabase_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedatabase',
            name='notes',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
